# -*- coding: utf-8 -*-
"""Blood GRoup Detection Useing FInger Prints.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YtnHK_-JdvDkWN0A27MW84jQkduRa_Gw
"""

# =========================================================
# 0️⃣ INSTALL DEPENDENCIES
# =========================================================
!pip install -q timm albumentations==1.3.1 roboflow opencv-python

# =========================================================
# 1️⃣ IMPORTS & SETUP
# =========================================================
import os, glob, random
import numpy as np
from collections import Counter
from PIL import Image
from tqdm.auto import tqdm
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler

import albumentations as A
from albumentations.pytorch import ToTensorV2

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

import timm
from roboflow import Roboflow

device = "cuda" if torch.cuda.is_available() else "cpu"
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)
print("🔥 Device:", device)

# =========================================================
# 2️⃣ DOWNLOAD DATASET (ROBOFLOW)
# =========================================================
rf = Roboflow(api_key="I2du50GUFMWkImaaH0Wm")   # 🔴 PUT YOUR API KEY
project = rf.workspace("ahsan-khan-iw5ip").project("blood-group-detection-kmolp")
dataset = project.version(1).download("folder")
dataset_path = dataset.location

# =========================================================
# 3️⃣ LOAD DATA & STRATIFIED SPLIT (70 / 15 / 15)
# =========================================================
def load_all_data(path):
    files, labels = [], []
    classes = sorted(os.listdir(os.path.join(path, "train")))
    for i, cls in enumerate(classes):
        for split in ["train", "valid", "test"]:
            p = os.path.join(path, split, cls)
            if os.path.exists(p):
                imgs = glob.glob(p + "/*")
                files.extend(imgs)
                labels.extend([i] * len(imgs))
    return files, labels, classes

files, labels, classes = load_all_data(dataset_path)

X_train, X_tmp, y_train, y_tmp = train_test_split(
    files, labels, test_size=0.30, stratify=labels, random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_tmp, y_tmp, test_size=0.50, stratify=y_tmp, random_state=42
)

# =========================================================
# 📊 CLASS-WISE DISTRIBUTION DISPLAY
# =========================================================
def show_distribution(name, y, classes):
    cnt = Counter(y)
    print(f"\n{name} SET: {len(y)} samples")
    for i, cls in enumerate(classes):
        print(f"  {cls}: {cnt[i]}")

print("\n================ DATASET SPLIT DISTRIBUTION ================")
show_distribution("TRAIN", y_train, classes)
show_distribution("VALIDATION", y_val, classes)
show_distribution("TEST", y_test, classes)
print("============================================================")

# =========================================================
# 4️⃣ DATA AUGMENTATION
# =========================================================
IMG = 224

train_tfms = A.Compose([
    A.Resize(256, 256),
    A.CenterCrop(IMG, IMG),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.4),
    A.Normalize(),
    ToTensorV2()
])

val_tfms = A.Compose([
    A.Resize(256, 256),
    A.CenterCrop(IMG, IMG),
    A.Normalize(),
    ToTensorV2()
])

# =========================================================
# 5️⃣ DATASET & DATALOADERS
# =========================================================
class FingerprintDataset(Dataset):
    def __init__(self, files, labels, tfm):
        self.files, self.labels, self.tfm = files, labels, tfm
    def __len__(self): return len(self.files)
    def __getitem__(self, i):
        img = np.array(Image.open(self.files[i]).convert("RGB"))
        img = self.tfm(image=img)["image"]
        return img, torch.tensor(self.labels[i])

cnt = Counter(y_train)
weights = [1.0 / cnt[l] for l in y_train]
sampler = WeightedRandomSampler(weights, len(weights), replacement=True)

train_dl = DataLoader(
    FingerprintDataset(X_train, y_train, train_tfms),
    batch_size=16, sampler=sampler, num_workers=2, pin_memory=True
)
val_dl = DataLoader(
    FingerprintDataset(X_val, y_val, val_tfms),
    batch_size=32, num_workers=2, pin_memory=True
)
test_dl = DataLoader(
    FingerprintDataset(X_test, y_test, val_tfms),
    batch_size=32, num_workers=2, pin_memory=True
)

# =========================================================
# 6️⃣ STRONG HYBRID MODEL
# =========================================================
class StrongHybrid(nn.Module):
    def __init__(self, n):
        super().__init__()
        self.eff = timm.create_model("tf_efficientnetv2_s.in21k", pretrained=True, num_classes=0)
        self.cnx = timm.create_model("convnext_small", pretrained=True, num_classes=0)
        self.bn1 = nn.BatchNorm1d(self.eff.num_features)
        self.bn2 = nn.BatchNorm1d(self.cnx.num_features)
        self.head = nn.Sequential(
            nn.Linear(self.eff.num_features + self.cnx.num_features, 1024),
            nn.BatchNorm1d(1024),
            nn.GELU(),
            nn.Dropout(0.35),
            nn.Linear(1024, n)
        )

    def forward(self, x):
        f1 = self.bn1(self.eff(x))
        f2 = self.bn2(self.cnx(x))
        return self.head(torch.cat([f1, f2], dim=1))

model = StrongHybrid(len(classes)).to(device)
print("✅ Model initialized")

# =========================================================
# 7️⃣ LOSS, OPTIMIZER, SCHEDULER
# =========================================================
class_weights = torch.tensor([1.0 / cnt[i] for i in range(len(classes))], device=device)

criterion = nn.CrossEntropyLoss(weight=class_weights, label_smoothing=0.05)

optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4, weight_decay=1e-4)

scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(
    optimizer, T_0=10, T_mult=2, eta_min=1e-6
)

scaler = torch.cuda.amp.GradScaler()

# =========================================================
# 8️⃣ TRAINING (STORE ACC & LOSS)
# =========================================================
EPOCHS = 70
patience, wait = 10, 0
best_val_acc = 0.0

train_acc_hist, val_acc_hist = [], []
train_loss_hist, val_loss_hist = [], []

for epoch in range(EPOCHS):
    model.train()
    tr_p, tr_y = [], []
    train_loss = 0.0

    for x, y in tqdm(train_dl, desc=f"Epoch {epoch+1}/{EPOCHS}"):
        x, y = x.to(device), y.to(device)
        optimizer.zero_grad()

        with torch.cuda.amp.autocast():
            out = model(x)
            loss = criterion(out, y)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        train_loss += loss.item()
        tr_p += out.argmax(1).cpu().tolist()
        tr_y += y.cpu().tolist()

    scheduler.step()
    train_loss /= len(train_dl)
    train_acc = accuracy_score(tr_y, tr_p)

    model.eval()
    v_p, v_y = [], []
    val_loss = 0.0

    with torch.no_grad():
        for x, y in val_dl:
            x, y = x.to(device), y.to(device)
            out = model(x)
            loss = criterion(out, y)
            val_loss += loss.item()
            v_p += out.argmax(1).cpu().tolist()
            v_y += y.cpu().tolist()

    val_loss /= len(val_dl)
    val_acc = accuracy_score(v_y, v_p)

    train_acc_hist.append(train_acc)
    val_acc_hist.append(val_acc)
    train_loss_hist.append(train_loss)
    val_loss_hist.append(val_loss)

    print(f"📊 Epoch {epoch+1}: TrainAcc={train_acc:.4f}, ValAcc={val_acc:.4f}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        wait = 0
        torch.save(model.state_dict(), "best_model.pth")
        print("✅ Best model saved")
    else:
        wait += 1
        if wait >= patience:
            print("🛑 Early stopping")
            break

# =========================================================
# 9️⃣ TEST-TIME AUGMENTATION (TTA)
# =========================================================
model.load_state_dict(torch.load("best_model.pth"))
model.eval()

tp, ty = [], []
with torch.no_grad():
    for x, y in test_dl:
        x, y = x.to(device), y.to(device)
        o1 = model(x)
        o2 = model(torch.flip(x, dims=[3]))
        o = (o1 + o2) / 2
        tp += o.argmax(1).cpu().tolist()
        ty += y.cpu().tolist()

print("\n🎯 FINAL TEST ACCURACY:", accuracy_score(ty, tp))
print("\n📄 CLASSIFICATION REPORT:\n")
print(classification_report(ty, tp, target_names=classes))

# =========================================================
# 🔟 PLOT ACCURACY & LOSS
# =========================================================
epochs = range(1, len(train_acc_hist) + 1)

plt.figure(figsize=(8,5))
plt.plot(epochs, train_acc_hist, label="Train Accuracy")
plt.plot(epochs, val_acc_hist, label="Validation Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Training vs Validation Accuracy")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))
plt.plot(epochs, train_loss_hist, label="Train Loss")
plt.plot(epochs, val_loss_hist, label="Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

# =========================================================
# 1️⃣1️⃣ SAVE FINAL MODEL
# =========================================================
torch.save(model.state_dict(), "HybridBloodGroupNet_Final.pth")
print("✅ Final model saved successfully")

import matplotlib.pyplot as plt

epochs = range(1, len(train_acc_hist) + 1)

plt.figure(figsize=(8,5))
plt.plot(epochs, train_acc_hist, label="Training Accuracy", linewidth=2)
plt.plot(epochs, val_acc_hist, label="Validation Accuracy", linewidth=2)
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Training vs Validation Accuracy")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))
plt.plot(epochs, train_loss_hist, label="Training Loss", linewidth=2)
plt.plot(epochs, val_loss_hist, label="Validation Loss", linewidth=2)
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(ty, tp)

plt.figure(figsize=(8,6))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=classes,
    yticklabels=classes
)
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix for Blood Group Classification")
plt.tight_layout()
plt.show()

from sklearn.metrics import precision_recall_fscore_support

p, r, f1, _ = precision_recall_fscore_support(ty, tp)

x = np.arange(len(classes))
width = 0.25

plt.figure(figsize=(10,5))
plt.bar(x - width, p, width, label="Precision")
plt.bar(x, r, width, label="Recall")
plt.bar(x + width, f1, width, label="F1-score")

plt.xticks(x, classes, rotation=45)
plt.ylabel("Score")
plt.title("Class-wise Precision, Recall, and F1-score")
plt.legend()
plt.tight_layout()
plt.show()

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc

y_bin = label_binarize(ty, classes=range(len(classes)))

plt.figure(figsize=(8,6))
for i, cls in enumerate(classes):
    fpr, tpr, _ = roc_curve(y_bin[:, i], np.array(tp) == i)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{cls} (AUC={roc_auc:.2f})")

plt.plot([0,1], [0,1], 'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves for Blood Group Classification")
plt.legend()
plt.grid(True)
plt.show()

lrs = [scheduler.get_last_lr()[0] for _ in range(len(train_acc_hist))]

plt.figure(figsize=(8,5))
plt.plot(epochs, lrs)
plt.xlabel("Epochs")
plt.ylabel("Learning Rate")
plt.title("Learning Rate Schedule (Cosine Annealing)")
plt.grid(True)
plt.show()

confidences = []

with torch.no_grad():
    for x, _ in test_dl:
        x = x.to(device)
        probs = torch.softmax(model(x), dim=1)
        confidences.extend(probs.max(1).values.cpu().numpy())

plt.figure(figsize=(8,5))
plt.hist(confidences, bins=30)
plt.xlabel("Prediction Confidence")
plt.ylabel("Frequency")
plt.title("Prediction Confidence Distribution")
plt.grid(True)
plt.show()

from sklearn.manifold import TSNE

features, labels_tsne = [], []

model.eval()
with torch.no_grad():
    for x, y in test_dl:
        x = x.to(device)
        f1 = model.eff(x)
        f2 = model.cnx(x)
        f = torch.cat([f1, f2], dim=1)
        features.append(f.cpu())
        labels_tsne.extend(y.numpy())

features = torch.cat(features).numpy()

tsne = TSNE(n_components=2, random_state=42)
emb = tsne.fit_transform(features)

plt.figure(figsize=(8,6))
for i, cls in enumerate(classes):
    idx = np.array(labels_tsne) == i
    plt.scatter(emb[idx,0], emb[idx,1], label=cls, alpha=0.6)

plt.legend()
plt.title("t-SNE Visualization of Learned Feature Space")
plt.tight_layout()
plt.show()

import pandas as pd
from collections import Counter

def make_dist_table(y, split_name):
    cnt = Counter(y)
    return pd.DataFrame({
        "Split": split_name,
        "Class": classes,
        "Samples": [cnt[i] for i in range(len(classes))]
    })

df_train = make_dist_table(y_train, "Train")
df_val   = make_dist_table(y_val, "Validation")
df_test  = make_dist_table(y_test, "Test")

df_dataset = pd.concat([df_train, df_val, df_test], ignore_index=True)
df_dataset

from sklearn.metrics import classification_report
import pandas as pd

report = classification_report(
    ty, tp,
    target_names=classes,
    output_dict=True
)

df_classwise = pd.DataFrame(report).transpose()
df_classwise = df_classwise.iloc[:-3]  # remove avg rows
df_classwise

macro_precision = report["macro avg"]["precision"]
macro_recall    = report["macro avg"]["recall"]
macro_f1        = report["macro avg"]["f1-score"]
accuracy        = accuracy_score(ty, tp)

pd.DataFrame({
    "Metric": ["Accuracy", "Macro Precision", "Macro Recall", "Macro F1-Score"],
    "Value": [
        f"{accuracy*100:.2f}%",
        f"{macro_precision:.4f}",
        f"{macro_recall:.4f}",
        f"{macro_f1:.4f}"
    ]
})

